# Creates the security_forecasts table for caching Kronos AI price predictions.
#
# Each row represents a complete 7-day (or custom horizon) forecast for one
# security, generated by the Kronos foundation model. Forecasts are refreshed
# daily by KronosForecastJob.
#
# RELATIONSHIP:
#   securities (1) ──< security_forecasts
#
# AFTER DEPLOY:
#   bin/rails db:migrate
#
class CreateSecurityForecasts < ActiveRecord::Migration[7.2]
  def change
    create_table :security_forecasts, id: :uuid, default: -> { "gen_random_uuid()" } do |t|
      t.references :security, null: false, foreign_key: true, type: :uuid

      t.string  :ticker,        null: false              # denormalised for fast lookup
      t.string  :model_version, null: false              # e.g. "kronos-mini"
      t.integer :horizon_days,  null: false, default: 7  # trading days forecasted
      t.datetime :generated_at, null: false              # when the model ran

      # predictions: JSON array of { date, predicted_close, confidence_low, confidence_high }
      t.jsonb :predictions, null: false, default: []

      t.timestamps
    end

    # One active forecast per security / model / horizon combination.
    # Upsert by deleting old row and inserting new on each job run.
    add_index :security_forecasts,
              %i[security_id model_version horizon_days],
              unique: true,
              name: "idx_security_forecasts_unique"

    add_index :security_forecasts, :ticker
  end
end
